### PR TITLE
synced upstream (3rd try in merging)

### PR DESCRIPTION
**Pull request by JustinhSE**
synced upstream and able to merge

### CODE REVIEW

**Comment by xl4624** [comment]
try running:
```bash
git remote add upstream git@github.com:codicate/underclassmen-internships.git
git fetch upstream
git checkout main
git reset --hard upstream/main
git checkout -b <branch-name> # replace <branch-name> with the name of your branch
```
to basically make sure that you are synced with the latest upstream repo

then make the change in your local repo and run:
```bash
git add .
git commit -m "commit message here"
git push
git checkout main # to go back to your remote main branch
```
then you should be able to see on github it'll automatically ask you if you want to create a PR

**Comment by JustinhSE** [comment]
for the first command @xl4624 it says "error: remote upstream already exists."

**Comment by JustinhSE** [comment]
* just closed pull requests

**Comment by JustinhSE** [comment]
redid it so it is clearer

**Pull request closed without merging**
