### PR TITLE
Jane Street Immersion Program Now Open

### PR DESCRIPTION
**Pull request by JustinhSE**
Changed the fellowship to being open & closed Google STEP

### CODE REVIEW

**Comment by Julian048** [comment]
lgtm except that JSIP is freshman only 
"
To qualify for this program, you must be a current first-year undergraduate student (Class of 2027) who intends to complete your college or university’s introduction to computer science course(s) by June 2024, and has experienced barriers to access and opportunity within computer science.
"
by between first and second year they mean they summer in between is when you would be doing the program

**Comment by JustinhSE** [comment]
@Julian048 "JSIP is intended for undergraduate students between their first and second years who are passionate about computer science and have also experienced barriers to opportunity within the field."

**Comment by JustinhSE** [comment]
I see what you mean, I read it wrong, they could have said rising sophomores....

**Comment by codicate** [comment]
Thank you!

**Pull request merged**
